sudo: required

services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

python:
  - '3.9'

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=service-account.json
  - gcloud components install kubectl
  - gcloud config set project PROJECT_ID
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials sample-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t sayemsarkar123/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sayemsarkar123/multi-client npm run test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
