sudo: required

services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - sudo apt-get install build-essential checkinstall
  - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
  - cd /opt
  - sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
  - sudo tar xzf Python-3.8.12.tgz
  - cd Python-3.8.12
  - sudo ./configure --enable-optimizations
  - sudo make altinstall
  - cd $TRAVIS_BUILD_DIR
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=service-account.json
  - gcloud components install kubectl
  - gcloud config set project multi-k8s-405309
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t sayemsarkar123/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sayemsarkar123/multi-client npm run test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
